# Generated by Django 2.1.2 on 2018-10-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gerenciador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='fk_conta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
