# Generated by Django 2.1.2 on 2018-10-15 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gerenciador', '0002_cadastro_fk_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='advogado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='data_inclusao',
            field=models.DateTimeField(auto_now=True, verbose_name='Incluido em'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='fk_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gerenciador.autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='fk_conta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='segredo',
            field=models.BooleanField(default=False),
        ),
    ]
