# Generated by Django 2.1.2 on 2018-10-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gerenciador', '0005_auto_20181026_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
