# Generated by Django 2.1.2 on 2018-11-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gerenciador', '0006_auto_20181029_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='autor',
            new_name='nome_autor',
        ),
    ]
