# Generated by Django 2.1.2 on 2018-11-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gerenciador', '0007_auto_20181104_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusgeral',
            name='fk_autor',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='fk_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gerenciador.autor'),
        ),
    ]
