# Generated by Django 2.1.3 on 2018-11-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gerenciador', '0008_auto_20181112_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['data_inclusao']},
        ),
        migrations.AddField(
            model_name='statusgeral',
            name='notas',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='statusgeral',
            name='status_acompanhamento',
            field=models.IntegerField(choices=[(1, 'I - Inicial'), (2, 'II - Liminar'), (3, 'III - Mandado Expedido'), (4, 'IV - Mandado Devolvido'), (5, 'VI - Novo Mandado'), (6, 'VII - Baixado')], default=1),
        ),
    ]
